# Generated by Django 2.2.3 on 2019-08-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.FileField(default='', upload_to='images/'),
        ),
    ]
